pr:
  autoCancel: "true"
  branches:
    include:
    - Test
    - main
  paths:
    exclude:
    - README.md
    - azure-pipelines.yml
stages:
- stage: TestSalesforceOrg
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/Test'))
  jobs:
  - job: DeployTestOrg
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '14.x'
          checkLatest: true
      - bash: 
          npm install sfdx-cli --global
        displayName: Install Salesforce CLI
      - bash:
            sfdx config:set restDeploy=false --global
        displayName: Use SOAP API for Deployment
      - bash:
            sfdx force:auth:jwt:grant --clientid 3MVG9fe4g9fhX0E698chiT3XenKjdy3fsnB385FMfiAI4ZeBzPOQZqOzAtEuxlZrRLwa04TOraAXR3dgX8puB --jwtkeyfile ./bin/server.key --username prasad12@tcs.com --instanceurl https://login.salesforce.com
        displayName: Authorize Salesforce DeployTestOrg Org
      - bash:
            sfdx force:source:deploy -p force-app -w 10 -u prasad12@tcs.com
        displayName: Deploy source code to DeployTestOrg Org